PERF_API_URL: "http://localhost/v2/api/cicd/"
api_params: 
 sla: 
  pageLoadTime: 4000
 baseline: 
  days: 7
  perc: 75
  padding: 1.2
 flags: 
  assertBaseline: true
  debug: false
  esTrace: false
  esCreate: false
  passOnFailedAssert: false
 log: 
  test_info: "Demo SeleniumConf17"
  env_tester: "Windows"
  browser: "Demo browser"
  env_target: "PROD"
  team: "SELENIUM TEAM"